sonar.projectKey=Shavej_ali24_resturant_app_frontend
sonar.organization=shavez-ali24

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/*.config.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8